site_name: Shotover Proxy
nav:
  - Home: index.md
  - "User Guide":
      - "Introduction": "user-guide/introduction.md"
      - "Getting Started": "user-guide/getting-started.md"
      - "Concepts": "user-guide/concepts.md"
      - "Configuration": "user-guide/configuration.md"
  - "Transforms": "transforms/transforms.md"
  - "Examples":
      - "Redis": "examples/redis-clustering.md"
  - "Contributing": "contributing.md"

markdown_extensions:
  - toc:
      permalink: "#"

theme:
  logo: logo_48x48.png
  favicon: logo_48x48.png
  name: material
#theme:
#  name: readthedocs
#  highlightjs: true
#  hljs_languages:
#    - yaml
#    - rust
