site_name: Shotover Proxy
nav:
  - Home: index.md
  - 'User Guide':
      - 'Introduction': 'user-guide/introduction.md'
      - 'Getting Started': 'user-guide/getting-started.md'
      - 'Concepts': 'user-guide/concepts.md'
      - 'Configuration': 'user-guide/configuration.md'
      - 'Functions': 'user-guide/functions.md'
  - 'Transforms': 'transforms/transforms.md'
  - 'Examples':
      - 'Redis': 'examples/redis-clustering.md'

markdown_extensions:
  - toc:
      permalink: "#"

theme:
  name: material

#theme:
#  name: readthedocs
#  highlightjs: true
#  hljs_languages:
#    - yaml
#    - rust