[package]
name = "test-helpers"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
cassandra-cpp-driver-tests = ["cassandra-cpp"]
rdkafka-driver-tests = ["rdkafka"]

[dependencies]
tracing.workspace = true
subprocess.workspace = true
tokio-bin-process.workspace = true
cdrs-tokio.workspace = true
cassandra-protocol.workspace = true
cassandra-cpp = { version = "2.0.0", default-features = false, features = ["log"], optional = true }
scylla.workspace = true
openssl.workspace = true
bytes.workspace = true
ordered-float.workspace = true
tokio.workspace = true
uuid.workspace = true
redis.workspace = true
tokio-io-timeout = "1.1.1"
tokio-openssl.workspace = true
itertools.workspace = true
reqwest.workspace = true
tracing-subscriber.workspace = true
serde_yaml.workspace = true
anyhow.workspace = true
rcgen.workspace = true
rdkafka = { version = "0.36", features = ["cmake-build"], optional = true }
docker-compose-runner = "0.3.0"
# TODO: make scylla reexport these so we dont have to import random old versions
bigdecimal = "0.2.2"
num-bigint = "0.3.0"
