[package]
name = "test-helpers"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
cassandra-cpp-driver-tests = ["cassandra-cpp"]

[dependencies]
tracing.workspace = true
subprocess.workspace = true
tokio-bin-process = "0.2.0"
cdrs-tokio.workspace = true
cassandra-protocol.workspace = true
cassandra-cpp = { version = "2.0.0", optional = true }
scylla.workspace = true
openssl.workspace = true
bytes.workspace = true
ordered-float = { version = "3.0.0", features = ["serde"] }
tokio.workspace = true
uuid.workspace = true
redis.workspace = true
tokio-io-timeout = "1.1.1"
tokio-openssl.workspace = true
inferno = { version = "0.11.15", default-features = false, features = ["multithreaded", "nameattr"] }
itertools.workspace = true
reqwest.workspace = true
tracing-subscriber.workspace = true
serde_yaml.workspace = true
anyhow.workspace = true
rcgen.workspace = true
docker-compose-runner = "0.1.0"
