---
sources:
  redis_prod:
    Redis:
      batch_size_hint: 10
      listen_addr: "127.0.0.1:6379"
chain_config:
  redis_chain:
    - TunableConsistencyConfig:
        write_consistency: 2
        read_consistency: 2
        route_map:
          one:
            - RedisTimestampTaggerConfig: []
            - RedisCodecConfiguration:
                remote_address: "127.0.0.1:3331"
          two:
            - RedisTimestampTaggerConfig: []
            - RedisCodecConfiguration:
                remote_address: "127.0.0.1:3332"
          three:
            - RedisTimestampTaggerConfig: []
            - RedisCodecConfiguration:
                remote_address: "127.0.0.1:3333"
named_topics:
  testtopic: 5
source_to_chain_mapping:
  redis_prod: redis_chain