version: "3.3"
services:
  redis-one:
    image: library/redis:5.0.9
    ports:
      - "6379:6379"
  cassandra-one:
    image: shotover-int-tests/cassandra:4.0.6
    ports:
      - "9043:9042"
    environment:
      MAX_HEAP_SIZE: "400M"
      MIN_HEAP_SIZE: "400M"
      HEAP_NEWSIZE: "48M"
