name: publish to github pages

on:
  push:
    # Trigger when there is a new commit on main branch
    branches: [ main ]
    # also trigger when a new release tag is added to the repo
    tags:
      - "v*"

# Cancel already running jobs
concurrency:
  group: publish_to_pages_${{ github.head_ref }}
  cancel-in-progress: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: Publish website to Github Pages
            runner: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.setup_pages.outputs.base_url }}
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    steps:
    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
    - name: Build website
      run: cargo run -p website
    - name: Setup Pages
      uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v4
    - name: Upload pages
      uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4
      with:
        path: 'website/root'
    - name: Deploy pages
      uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
